### ISSUE TITLE
Missing word in lab 2 reflection 

### ISSUE THREAD

**Issue by burgess01** [Allegheny-Computer-Science-102-F2020/cs102-F2020-plans#10]
**Describe the bug**

I found this bug in the reflection.md file for our second lab. The sentence states, ' After completing this assignment, what is task that you want to practice more? Why?'. This sentence should have an 'a' after 'is' and before 'task' in order to have correct grammar.

**State the reproduction steps**

Steps to reproduce the behavior of the bug that you found:

Go to the lab 2 starter template, click view code above the cs102 header, click on the writing folder, and then click on reflection.md. Once you are there, you can scroll down until you see the question with the error.
**Explain the expected behavior**

I expected the question to have correct grammar.

**Explain your execution environment**

I am sitting in my dorm, using a Mac model A2289. I have python version 3.8.5 installed. I am using the VSCode extensions required for the class.

**Comment by gkapfham** [comment]
Hello @burgess01, thanks for reporting this defect. I will aim to patch this sentence soon in the current assignment repositories and then for the upcoming assignments as well. Thanks!
