### ISSUE TITLE
Wrong cd for lab 4

### ISSUE THREAD

**Issue by watson02** [Allegheny-Computer-Science-102-F2020/cs102-F2020-plans#12]
In the lab 4 read me it reads "Now, making sure that you are in your "home base" directory for this laboratory assignment, you need to install the dependencies for the iterator program that you will implement, debug, and observe. To complete this step you need to type cd iterator and then poetry install"

Please provide a clear and concise description of what the bug is and where you
found it. Is the bug in an assignment? Is it a bug in a video? Is there a bug in
the course slides? For each of these questions, please explain which one. If you
have found a bug in a different type of course material, please explain it in
detail.

The text should read that we should open the cd data summarizer instead of cd interator.

Steps to reproduce the behavior of the bug that you found:

with cd integrator is says iterator is not found

Please provide a clear and concise description of what you expected to happen
and why you thought that was the most likely thing to happen.

I expected for the read me to read cd datasummeraizer

Please provide a detailed description of your execution environment, including
the make and model of your laptop, your laptop's operating system, the version
of Python installed on your laptop, and the current extensions that you are
using in VSCode. If there are any other relevant details, please provide them in
this section of the issue report.

My laptop is MacOs. Python 3.8.5 is installed. 

Please provide any additional context about the bug in this section. Remember,
the more information that you provide the better the instructor and the student
technical leaders can work to assist you with your problems!

**Comment by gkapfham** [comment]
Hi @watson02 thanks for reporting this bug! What do you suggest should be the exact command? You have suggested a `cd` command with a directory that contains a space in it. Is that what you intended?

**Comment by watson02** [comment]
The exact command should be cd datasummeraizer
