### ISSUE TITLE
Incorrect file name in Lab 5 reflection question.

### ISSUE THREAD

**Issue by burgess01** [Allegheny-Computer-Science-102-F2020/cs102-F2020-plans#14]
**Describe the bug**

This is a bug with the third reflection question, the prompt mentions the display module, but there isn't a display module.

**State the reproduction steps**

Steps to reproduce the behavior of the bug that you found:

Open up Lab 5 in virtual code, then navigate to the reflection.md file, and then scroll down to the first function question.

**Explain the expected behavior**

I expected the question to mention the transform module, not a display module.

**Explain your execution environment**

I am sitting in my dorm, using a Mac model A2289. I have python version 3.8.5 installed. I am using the VSCode extensions required for the class.

**Comment by gkapfham** [comment]
Thanks for reporting this but in n the reflection file! I'll fix this for this assignment and swim two said this problem in future assignments. 👍
