### ISSUE TITLE
wrong cd for Lab 5

### ISSUE THREAD

**Issue by burgess01** [Allegheny-Computer-Science-102-F2020/cs102-F2020-plans#15]
**Describe the bug**

This is a bug in the 5th lab. The readme file says to use the cd iterator command, but this is inaccurate as there is no iterator directory to go to.

**State the reproduction steps**

Open Lab 5 in Virtual code, go to the README.md file and scroll down to where it is talking about what cd command to use.

**Explain the expected behavior**

I expected the README to say to use 'cd superdatasummarizer'.

**Explain your execution environment**

I am sitting in my dorm, using a Mac model A2289. I have python version 3.8.5 installed. I am using the VSCode extensions required for the class.

**Comment by gkapfham** [comment]
Hi @burgess0! Thanks for reporting this but. I recently noticed this one  bug as well! I will try to fix it next week!
