### ISSUE TITLE
Missing word in the examination one file.

### ISSUE THREAD

**Issue by burgess01** [Allegheny-Computer-Science-102-F2020/cs102-F2020-plans#16]
**Describe the bug**

There is a missing word on the review bullet points for exam 1. The bullet point says 'How trace the execution of a Python function with debugging statements', while it should say 'How TO trace the execution of a Python function with debugging statements'.

**State the reproduction steps**

Steps to reproduce the behavior of the bug that you found:

Navigate to the main page of the plans directory, then click on the review file at the top of the page in the files section, and then click on the examination-one-review.md file. from there scroll down to the Debugging and Testing of Python Programs and look at the last bullet point.

**Explain the expected behavior**

I expected there to be a to in that sentence.

**Explain your execution environment**

I am sitting in my dorm, using a Mac model A2289. I have python version 3.8.5 installed. I am using the VSCode extensions required for the class.

**Comment by gkapfham** [comment]
Thanks for reporting this @burgess01. I will fix this issue next week, most likely.
