### ISSUE TITLE
Miss spelling in instructions

### ISSUE THREAD

**Issue by watson02** [Allegheny-Computer-Science-102-F2020/cs102-F2020-plans#3]
**Describe the bug**

In the instructions for fall 2020 course plan it reads "Use the GitHub issue tracker to submit feedback on the course, to ask technical questions, and to request the the instructor to create YouTube videos on technical topics related to Python programming and discrete structures." It says the twice.

**State the reproduction steps**

Steps to reproduce the behavior the bug that you found:
It should read "...and to request that the instructor to create YouTube videos..."

**Explain the expected behavior**

I excepted correct grammar.

**Explain your execution environment**

I am in my dorm room trying to complete the assignments assigned to me at 2 in the afternoon. My laptop is a MacBook Air, I have Python 3.8 installed, and I don't understand how to answer "the current extensions that you are using in VSCode".
Please provide a detailed description of your execution environment, including
the make and model of your laptop, your laptop's operating system, the version
of Python installed on your laptop, and the current extensions that you are
using in VSCode. If there are any other relevant details, please provide them in
this section of the issue report.

**Comment by gkapfham** [comment]
Hi @watson02 thanks for raising this issue, I really appreciate your hard work and attention to detail. Could I trouble you to please tell me which file contains the "the the" pattern that you are describing? If you could either give me the name of the file or the link to the file in the GitHub repository, it would be really helpful to me. Or, is this inside of the Slack workspace or in some other location? Overall, can you please clarify this further? Thanks! I will look forward to your response and will not close this issue until we have resolved the writing mistake.

**Comment by watson02** [comment]
![image](https://user-images.githubusercontent.com/70479210/92171642-78619980-ee09-11ea-96c8-fd9aef1dce39.png)

**Comment by gkapfham** [comment]
Hello @watson02, thanks for sharing this screenshot to illustrate where there was a writing mistake in the project board. I have fixed the writing mistake and you can find the updated project board at this site:

https://github.com/Allegheny-Computer-Science-102-F2020/cs102-F2020-plans/projects/1

Can you please confirm that my fix is acceptable? Once we fully resolve the issue I will mark it as closed. Thanks!

**Comment by watson02** [comment]
Ok and no problem.

**Comment by watson02** [comment]
Do I just press close? If not I don't know how to confirm that the issue was fixed

**Comment by gkapfham** [comment]
Hi @watson02, yes, it is fine for you to close the issue if you think that it is fixed. One nice thing about using GitHub Issue Tracker is that it keeps the issues around permanently even after they are closed! So, I will leave it to you to close the issue, okay? Thanks again for your help, it is greatly appreciated.
