### ISSUE TITLE
Instructions description

### ISSUE THREAD

**Issue by watson02** [Allegheny-Computer-Science-102-F2020/cs102-F2020-plans#4]
**Describe the bug**

In the instructions for what to do when filling out an issue for a bug report it says "Steps to reproduce the behavior the bug that you found".

**State the reproduction steps**

Steps to reproduce the behavior the bug that you found:
 It should read "Steps to reproduce the behavior of the bug that you found".

**Explain the expected behavior**

I excepted correct grammar.

**Explain your execution environment**

I am in my dorm room trying to complete the assignments assigned to me at 2 in the afternoon. My laptop is a MacBook Air, I have Python 3.8 installed, and I don't understand how to answer "the current extensions that you are using in VSCode".

**Comment by gkapfham** [comment]
Hello @watson02 thanks for raising this bug report, it is greatly appreciated! I have fixed the writing mistake that you discovered and, additionally, fixed one other writing mistake in a different issue tracker template. Can you please confirm that I have fixed the template in a fashion that meets your expectations? Once you confirm, then I will close this issue and mark it as resolved.

Finally, you asked about the "current extensions that you are using in VSCode" and what that phrase means.

Here is a screenshot of my VSCode setup when I am editing the `README.md` file for the CMPSC 102 course:

![image](https://user-images.githubusercontent.com/926029/92157851-0719ea80-edf9-11ea-9443-18230455efa7.png)

Do you see how I have clicked on the boxes icons that are on the left-hand side of the screen? That is the icon for the extensions that you are using in VSCode. For instance, I have installed the Live Share extension and the GitHub Pull Request extension.

If you were asking me a question about VSCode, then it would be useful for you to tell me which VSCode extensions you had installed. You can find them by clicking in the correct location in VSCode. Okay, please let me know if you have a follow on question by continuing the discussion in the issue tracker.
