### ISSUE TITLE
Incorrect grammar in lab 1 reflection prompt

### ISSUE THREAD

**Issue by caylora** [Allegheny-Computer-Science-102-F2020/cs102-F2020-plans#7]
**Describe the bug**

In the [lab 1 starter](https://github.com/Allegheny-Computer-Science-102-F2020/cs102-F2020-lab1-starter), the prompt in "reflection.md" contains the line "After completing this assignment, what is task that you want to practice more? Why?"
There is an "a" missing between "is" and "task."

**State the reproduction steps**

Steps to reproduce the behavior of the bug that you found:

Examine "reflection.md" in a text editor of your choosing, and locate the aforementioned section.

**Explain the expected behavior**

The line in question should read "After completing this assignment, what is a task that you want to practice more? Why?"

**Explain your execution environment**

Issue is unrelated to hardware or software, but my specs are as follows:
- Laptop: Dell Inspiron 15-3567
- OS: Ubuntu 20.04.1 LTS
- Python Version: 3.8.5
- Browser: Firefox 80.0.1 (64-bit)
- VSCode: 1.48.2
- VSCode Extensions:
  - Docker 1.5.0
  - Live Share 1.0.2740
  - Live Share Audio 0.1.85
  - Live Share Extension Pack 0.4.0
  - markdownlint 0.36.3
  - Python 2020.8.106424

**Provide any additional context**

I posted an issue on the lab 1 starter repository, then realized that it should have been posted here. My mistake!

**Comment by gkapfham** [comment]
Hello @caylora, thanks for raising this issue! Yes, this is a mistake, which I have fixed in the starter repository. I will make sure that future assignments do not have a mistake in this sentence. Thanks again for your help. I am going to close this issue but you can re-open it as needed if you think that the starter repo does not have a suitable fix.
