### ISSUE TITLE
POETRY INSTALL IMPORTANT

### ISSUE THREAD

**Issue by EstebanMendez01** [Allegheny-Computer-Science-102-F2020/cs102-F2020-plans#9]
**Describe the challenge that you are currently facing**

When I do the first part of the lab, cd to the rootfinder and try to enter "poetry install", the message that the terminal gives me is this: 
poetry install

[EnvCommandError]
Command ['C:\\Users\\Esteban Mendez\\Desktop\\labs 102\\computer-science-102-fall-2020-lab-2-EstebanMendez01\\rootfinder\\.venv\\Scripts\\python.exe', '-'] errored with the following return code 101, and output:
Unable to create process using 'C:\Users\Esteban Mendez\AppData\Local\Programs\Python\Python38\python.exe -'
input was : import sys

if hasattr(sys, "real_prefix"):
    print(sys.real_prefix)
elif hasattr(sys, "base_prefix"):
    print(sys.base_prefix)
else:
    print(sys.prefix)

**Explain the steps you have taken so far**

- I have talked to a TL and tried to solve it
- I have talked to a classmate and tried fixing it for 5 hours straight.
- I have read these webpages https://github.com/python-poetry/poetry/issues/2491, https://github.com/python-poetry/poetry/issues/2468, https://www.reddit.com/r/Python/comments/gqd5ct/poetry_install_fails_cant_find_sys/, https://github.com/python-poetry/poetry/issues/1492,https://github.com/python-poetry/poetry/issues/2629.
- I have uninstalled python and installed it again, one way from pyenv, windows store, and installer from python webpage. 
- I have uninstalled and installed poetry via powershell and git bash. 
- I have tried installing poetry with no developer actions `poetry install --no-dev`. 
- We have been installing and uninstalling every program to see if the problem is in the installation, but the results are the same. 

**Explain the expected behavior**

Expected to download all the packages from poetry so I can START the lab. 

Please provide a clear and concise description of what you expected to happen
when you were completing an assignment and why you thought that was the most
likely thing to happen. Make sure to explain how what you are currently seeing
as behavior is different than the behavior that you were expecting.

**Explain your execution environment**

I expected to download the packages and START the lab assignment. This has to happen because every student in the class got it to work. What I do is just cd to rootfinder and hit enter, next I type poetry install and hit enter and this message is displayed. 

poetry install

[EnvCommandError]
Command ['C:\\Users\\Esteban Mendez\\Desktop\\labs 102\\computer-science-102-fall-2020-lab-2-EstebanMendez01\\rootfinder\\.venv\\Scripts\\python.exe', '-'] errored with the following return code 101, and output:
Unable to create process using 'C:\Users\Esteban Mendez\AppData\Local\Programs\Python\Python38\python.exe -'
input was : import sys

if hasattr(sys, "real_prefix"):
    print(sys.real_prefix)
elif hasattr(sys, "base_prefix"):
    print(sys.base_prefix)
else:
    print(sys.prefix)

**Explain the timeline by which you need to have this issue resolved**

Not working in the installation on rootfinder folder, poetry install. 
- ASUS 
- System Model	TP550LAB
- OS Name	Microsoft Windows 10 Pro
- Python 3.8.5
- Extensions: 
- Live share
- Live share audio
- Live share extension pack
- Python

**Give the name of at least two members of the course who are willing to
partner with you to help you to resolve this issue**

I have already received help from Lancaster Wu and Kobe Coleman. I think they should help me because they are using windows, same as me. I think I need the help of the professor.
I have read these webpages https://github.com/python-poetry/poetry/issues/2491, https://github.com/python-poetry/poetry/issues/2468, https://www.reddit.com/r/Python/comments/gqd5ct/poetry_install_fails_cant_find_sys/, https://github.com/python-poetry/poetry/issues/1492,https://github.com/python-poetry/poetry/issues/2629. I have uninstalled python and installed it again, one way from pyenv, windows store, and installer from python webpage. I have uninstalled and installed poetry via powershell and git bash. I have tried installing poetry with no developer actions `poetry install --no-dev`. I have tried adding the environment variables on system and user, manually and automatically. I have restarted the terminals and tried using admin cmd and all the terminals to see if one would work, but none worked. 

**Provide any additional context**

- Lancaster Wu
- Osama Eltoum
- Kobe Coleman
- Ochirsaikhan Davaajambal

The VS Code, poetry is not working for me since they give me this rare error, that not even a TL could solve. The problem has made me install and uninstall every program to see if that works for me, but nothing. Also, I have tried using different terminals to see if it was the terminal, which was not working for me, but nothing.

**Comment by EstebanMendez01** [comment]
@gkapfham

**Comment by gkapfham** [comment]
@EstebanMendez01 does this issue report describe the concern that you are facing?

https://github.com/python-poetry/poetry/issues/2468

Also, please refer to this issue report as well:

https://github.com/python-poetry/poetry/issues/2491

I will try to review this in greater detail soon.

Please make sure that you see my note on Slack concerning ways in which you can improve this issue report. If you can please improve several aspects of this issue report it will help everyone to better diagnose and resolve this problem. Thanks!

**Comment by PaigeCD** [comment]
I believe that I'm having the same issue and it appears to be a path mismatch. It looks like it is looking for pypoetry through the path:
`['C:\\Users\\paige\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\rootfinder-oH-IO-Gj-py3.8\\Scripts\\python.exe', '-']`
But the path to my pypoetry file is:
`C:\Users\paige\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local`
I'm not sure how to fix this.

**Comment by gkapfham** [comment]
Hello @PaigeCD and @EstebanMendez01, could I trouble you to please try the newly provided Docker container and then report back as to whether or not you are able to run Poetry and Python commands inside of it? Thanks for your feedback, it is greatly appreciated.

**Comment by EstebanMendez01** [comment]
Hello @gkapfham I wanted to know if you could help me update and try the new Docker container, since I cannot make it work, it just does not update! And a message appears.

**Comment by hoishing** [comment]
as @PaigeCD  said, the problem is caused by a path mismatch. If you `where python` in CMD, the path returned is just a dummy reference created by Microsoft, its not a real python binary. To locate the correct python binary path, you can use python REPL in CMD, `import sys` then `sys.path`. The first path returned is the real python binary path. Put this path in windows PATH enviroment variable **ABOVE** the original `%USERPROFILE%\AppData\Local\Microsoft\WindowsApps`, then poetry will be able to use the correct python binary.
